### ISSUE TITLE
throw er; // Unhandled 'error' event (on v1.0.7)

### ISSUE THREAD

**Issue by MJ17** [agreatfool/swagger-spec-to-pdf#5] opened 2017-07-12 11:37 UTC
Hi, again.
I updated to 1.0.7
however getting almost the same error.

Please help.

$ swagger2pdf -v
1.0.7

$ swagger2pdf -s my_sample_swagger.json -o ./dump/
events.js:182
throw er; // Unhandled 'error' event
^

Error: spawn http-server ENOENT
at exports._errnoException (util.js:1014:11)
at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
at onErrorNT (internal/child_process.js:366:16)
at _combinedTickCallback (internal/process/next_tick.js:102:11)
at process._tickCallback (internal/process/next_tick.js:161:9)

**Comment by agreatfool** [comment] 2017-07-13 01:34
Error means node can't find `http-server`. Could you please check did `http-server` installed globally.

```
$ which http-server
/usr/local/Cellar/nvm/0.31.0/versions/node/v8.1.0/bin/http-server
```

In version 1.0.7 I just update the script to preinstall `http-server` before swagger2pdf.

If error keeps, please show me the installation info, like:

```
$ npm install -g swagger-spec-to-pdf

> swagger-spec-to-pdf@1.0.7 preinstall /usr/local/Cellar/nvm/0.31.0/versions/node/v8.1.0/lib/node_modules/swagger-spec-to-pdf
> npm i -g http-server

/usr/local/Cellar/nvm/0.31.0/versions/node/v8.1.0/bin/http-server -> /usr/local/Cellar/nvm/0.31.0/versions/node/v8.1.0/lib/node_modules/http-server/bin/http-server
/usr/local/Cellar/nvm/0.31.0/versions/node/v8.1.0/bin/hs -> /usr/local/Cellar/nvm/0.31.0/versions/node/v8.1.0/lib/node_modules/http-server/bin/http-server
+ http-server@0.10.0
updated 1 package in 24.506s
/usr/local/Cellar/nvm/0.31.0/versions/node/v8.1.0/bin/swagger2pdf -> /usr/local/Cellar/nvm/0.31.0/versions/node/v8.1.0/lib/node_modules/swagger-spec-to-pdf/bin/swagger2pdf

> electron-prebuilt@0.37.8 postinstall /usr/local/Cellar/nvm/0.31.0/versions/node/v8.1.0/lib/node_modules/swagger-spec-to-pdf/node_modules/electron-prebuilt
> node install.js

+ swagger-spec-to-pdf@1.0.7
added 153 packages in 122.327s
```

**Comment by agreatfool** [comment] 2017-07-13 01:38
Quick fix of your issue is manually installing `http-server`.
Do

```
$ npm install -g http-server
```

**Comment by agreatfool** [comment] 2017-07-13 01:39
@MJ17 Please let me know if you want to track this issue or just using the quick fix. If quick fix, I would close the issue.

**Comment by MJ17** [comment] 2017-07-13 04:34
Hmm, I installed 'http-server' globally
and I'm still getting the same error.
seems that quick fix doesn't work...
btw, I'm running on Windows OS


PS C:\User\pennj\Desktop> Get-Command http-server
CommandType    Name
- - - - - - - - - - -    - - - -
Application    http-server.cmd
Application    http-server

PS C:\User\pennj\Desktop> http-server
Starting up http-server, serving ./
Available on:
  http://{IP_ADDRESS}:8080
  http://127.0.0.1:8080
Hit CTRL-C to stop the server
http-server stopped.
PS C:\User\pennj\Desktop>

**Comment by agreatfool** [comment] 2017-07-13 04:53
Gotcha. Seems it's an issue of windows node. Since I have no windows machine, I cannot test & reproduce. 

Maybe you can search "node child_process spawn windows" with google.

Some ref:
[child_process.spawn for windows?](https://github.com/nodejs/node-v0.x-archive/issues/4240)
[child_process.spawn fails on Windows given a space in both the command and an argument](https://github.com/nodejs/node-v0.x-archive/issues/25895)

**Closed as completed** 2017-07-14 01:28 UTC

**Comment by AhtiAhde** [comment] 2017-11-23 13:08
I reproduced this issue with Linux Ubuntu 16.04
